service: synerbot

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  environment:
    API_USERID: ${file(./conf/config.${self:provider.stage}.json):API_USERID}
    API_USERNAME: ${file(./conf/config.${self:provider.stage}.json):API_USERNAME}
    API_ENDPOINT: ${file(./conf/config.${self:provider.stage}.json):API_ENDPOINT}

functions:
  giveMeInfo:
    description: Handler method for alexa voice enabled skill.
    handler: handler.giveMeInfo
    events:
      - alexaSkill
  ProvideMeInfo:
    description: Handler method for conversational lex bot.
    handler: handler.provideMeInfo
  greetConversationalBot:
    description: Handler method for greet lex bot.
    handler: handler.greetConversationalBot
  thankConversationalBot:
    description: Handler method for thank lex bot.
    handler: handler.thankConversationalBot